### ISSUE TITLE
insecure / weak CSRF token

### ISSUE THREAD

**Issue by DanielRuf** [NumanABi/webcop-firewall#4]
md5 is broken and `rand` is predictable and not a CSPRNG.

Use a proper CSRF generation library.

https://github.com/NumanABi/webcop-firewall/blob/master/en/admin/webshell-scanner.php#L320

**Comment by numanozdemircom** [comment]
Every page refreshing, system will generate a new CSRF token. So, it is nearly impossible to crack this token. I am closing this issue, if you can achieve to crack or bypass CSRF protection, please create a new issue. Will not fix for now, thanks.
